### PR TITLE
bleak backend, cross-platform bluetooth, no root required

### LINKED ISSUE #146: Consider asyncio bleak backend
https://github.com/hbldh/bleak is a cross-platform bluetooth interface using python's asyncio infrastructure.  The use of asyncio provides for more flexibility for the user.  The bleak api has native python implementations for linux, windows, and osx, requiring no calling out to other processes or asking the user for root access.

Using asyncio would probably mean breaking the current api.(although it could be faked with a shim that ran asyncio in another thread, the shim seems a significant chunk of non-muse-related code.) EDIT: in the PR, this shimming is handed off to another package, preserving the current api.

### PR DESCRIPTION
**Pull request by xloem**
fixes #146

EDIT: The PR that enables this when looking for devices is #149, so if you want to use bleak for everything you'll need both PRs.

### CODE REVIEW

**Comment by xloem** [comment]
I've merged this PR along with most of the others into https://github.com/xloem/muse-lsl/tree/dev , and resolved bugs on my system, but it still needs somebody else to test it.  What would help others have more capacity for pull request maintenance, merging, testing?

**Comment by jdpigeon** [comment]
This does sound very promising. However, I wasn't able to get a device successfully connected off of this branch with some cursory hacking this morning on my Ubuntu machine.

I look forward to doing some more testing and getting this stuff merged in when I have more time. Thanks again for all this work @xloem!

**Comment by xloem** [comment]
`pip3 install bleak` and `-b bleak`.  What OS are you using?  I've only tested bleak on linux.

**Comment by xloem** [comment]
I ran the live cd for Ubuntu 20.04.1 LTS (Focal Fossa) in a VM, forwarded my internal USB bluetooth device, turned on my Muse S (maybe it only works on the Muse S =S...), and did this:
```
sudo add-apt-repository universe
sudo apt-get install python3-pip git
git clone -b bleak https://github.com/xloem/muse-lsl
cd muse-lsl
sudo pip3 install .
sudo python3 -m muselsl stream -b bleak
```
I still use `sudo` because this PR doesn't include the other one that passes the backend to the scanner, so it still scans with pygatt.
My output from the last command (sorry if there is a typo, hand-copying from VM livecd terminal):
```
Searching for Muses, this may take up to 10 seconds...
Found device MuseS-1C52, MAC Address 00:55:DA:BB:1C:52
Connecting to MuseS-1C52: 00:55:DA:BB:1C:52...
Connected.
Streaming EEG...
```
I'll rebase this onto master soon.  I also see on shutdown there's a "Set changed size during iteration" error I should fix, on backends.py:28 .

**Comment by ErikBjare** [comment]
Just tested this and it works great. Although it still asks for password when looking for devices, which I side-stepped by simply forcing the code in list_muses to use the bluetoothctl approach (which should probably be the default if `bluetoothctl` is available on the system?).

**Comment by jdpigeon** [comment]
This PR looks very promising: could this potentially replace pygatt or even BlueMuse?

Glad to hear it's working on Linux. When I have more time I will give this a test on windows and Mac.

**Comment by xloem** [comment]
I believe it could replace all the other backends if desired.

**Comment by ErikBjare** [comment]
Me and @mrksbrg just tested it on Windows, and it seems to work there too! (which is great, since we were having issues with BlueMuse)

Would appreciate a speedy merge @jdpigeon :)

**Comment by ErikBjare** [comment]
One small issue I found: It doesn't seem to disconnect the Muse from Bluetooth when the program quits, leaving it connected indefinitely and unable to connect to again until the Muse is restarted (by hand).

**Comment by xloem** [comment]
When I made this I tried to make the changes kind of conservative, to not alter the codebase much.  I might be able to eventually find time some day to refactor muse-lsl to integrate bleak better, if that's desired.  Personally I have been working with the brainflow project myself a little more, which unifies many drivers under one hood.  We just got android client functionality for the openbci cyton dongle and other ftdi-based boards implemented.

**Comment by danielemarinazzo** [comment]
thanks! @xloem , are you able to see the AUX channel with a Muse 2, or do you confirm as @kowalej wrote in the Bluemuse readme that is not possible to plug an extra micro usb electrode into the charger as aux channel?

**Comment by xloem** [comment]
I'm sorry I haven't had time to look into the stays-connected-after-close issue.  That's an issue I saw others running into with various devices and Bluetooth libraries while working on this.

As mentioned in other links, I get an aux channel on my Muse S which is a Muse 2, in the bluetooth protocol transmissions, but I do not have an aux probe to test actual data.

**Comment by danielemarinazzo** [comment]
Great, thanks!

I am now trying it on Ubuntu but I get the following error

```
ImportError: this version of pandas is incompatible with numpy < 1.15.4
your numpy version is 1.13.3.
```


while in fact the numpy version is 1.20

**Comment by xloem** [comment]
could maybe auxiliary requests for assistance tag me in an issue to not pollute the PR too much?  it's pretty clear the maintainers are strapped for capacity merging this.

the error you report doesn't seem related to this PR: it had to find that numpy version number from somewhere, so there is likely a rogue numpy install somewhere in your system.  you might be in or not in a virtualenv, thinking the opposite.  otherwise the path would be to diagnose whatever is importing pandas and see what generates that number.

**Comment by xloem** [comment]
@alexandrebarachant @jdpigeon How does this PR stand with you guys? Are you still available to engage in maintenance on this repo?

Personally, it can be very hard for me to engage this work, so it's good to know what the best changes to make are. Would this be more mergeable if I changed more of the codebase to rely on bleak as a single backend?

I ask because my fork at https://github.com/xloem/muse-lsl has been getting a little dev activity from other people, but not enough to really consider it a replacement or anything. It would be great if our codebases could merge somehow.

**Comment by jdpigeon** [comment]
Hey @xloem, I agree completely that merging our two codebases would be best. I let this languish because I was putting off getting my old dusty muse out of storage and trying it out first hand. However, at this point I think it'd be fair to give it a trust stamp and bring it into muse-lsl.

We should probably make it the default backend, eh? IIUC, It's the safest option cross-platform? With a version number bump and the update to making it default I'd be happy to merge and push to pypi.

**Comment by xloem** [comment]
@jdpigeon This sounds great.

I've changed helpers.py to always default to bleak. I'm not sure whether anybody has tested on macos, although it may be an upstream issue with bleak if a platform doesn't work.

It looks like organisation-wise helpers.py should maybe merge with my backends.py for now, but maybe it's more important to merge this very old PR, if it's good.

**Comment by ErikBjare** [comment]
Awesome, really happy to see this merged! 

Thank you @xloem and @jdpigeon!

**Pull request merged**
