### PR TITLE
[MRG] Changed matplotlib backend to PyQt5Agg

### PR DESCRIPTION
**Pull request by Hororohoruru**
Takes care of issue #81, but I'm not sure it is a common issue

### CODE REVIEW

**Comment by alexandrebarachant** [comment]
What OS are you using ? I'm not sure this is the ideal solution, and it might break others workflow.

**Comment by Hororohoruru** [comment]
I'm currently using Ubuntu 18.04. I agree with you, but since it is not an error thrown by the script, it might be difficult to handle correctly

**Comment by alexandrebarachant** [comment]
i'm rooting for an issues with dependencies. Last time i run the script on ubuntu I had no trouble with TkAgg. can you check online if other poeple ran into the same problem with matplotlib and see if this can be sove by updating a package ?

**Comment by Hororohoruru** [comment]
It doesn't seem to be any trend. I find ppl having the same issue with other backends, so usually they change backends to take care of it. Since it is a problem with matplotlib, this PR can be closed.

**Comment by alexandrebarachant** [comment]
One solution would be to add an extra argument so that you can switch
backend. When you run the script.

**Comment by Hororohoruru** [comment]
Good idea! on it

**Comment by Hororohoruru** [comment]
Anytime! Thanks for the feedback

**Pull request merged**
