### PR TITLE
Add control, telemetry, accelerometer and gyroscope handlers

### PR DESCRIPTION
**Pull request by pdpino**
I added handlers for control (that are responses from the muse to sent commands), telemetry (battery, temperature and stuff), accelerometer and gyroscope messages from the device.
Some comments: 
- I used some constants that @urish used in https://github.com/urish/muse-js, to get the correct units I presume (all the credits to him!)
- In the constructor of the `Muse` class I think that the `eeg`, `control`, `telemetry`, `accelero` and `giro` parameters should be deprecated, and instead subscribe to each channel when a callback is provided. Also the callback for eeg could be called `callback_eeg`. This changes are not backward-compatible so I didn't do them, but I can do them if you want :smile: 

Also, I did a minor refactor when writing commands to muse, only one method in the Muse class handles the writing to the device.

UPDATE: I added a method in the Muse class to send a command to the device asking for control information. The device will return data like battery status, device name, preset selected, and more.

### CODE REVIEW

**Comment by alexandrebarachant** [comment]
Thanks a lot.

@hubertjbanville : would you have time to review and test this PR ? I think it will be a great addition to muse-lsl

**Comment by hubertjbanville** [comment]
Very cool PR @pdpino :)

@alexandrebarachant : yes I'll take a look!

**Comment by hubertjb** [comment]
@pdpino here are a few ideas, let me know what you think:

- The callback APIs are not consistent. E.g., for EEG it's (`data`, `timestamps`), but it's the opposite for acc and gyro: (`timestamp`, `data`). These could be made the same.
- We could simplify the class API by removing the `eeg`, `control`, `telemetry`, `accelero` and `giro` arguments, and instead subscribe to the stream if there is a valid callback argument for the corresponding stream parameter, e.g., if `callback_eeg` is not None, then subscribe to the EEG stream; if `callback_eeg` is None though don't subscribe to it.
- I guess you might have modified `muse-lsl.py` to test these changes? We should probably include these changes here so by default muse-lsl subscribes to all available data streams, and streams acc and gyro as well to LSL.
- Similarly, it'd be great to be able to see these other streams in `lsl-viewer.py` by default or as an option.
- Finally, for consistency with the Muse documentation, I think we should replace `accelero`, and `giro` by `acc` and `gyro`, respectively.

I tested the streaming quickly and it worked well on Linux. Thanks again for your PR!

**Comment by pdpino** [comment]
I agree!

> The callback APIs are not consistent. E.g., for EEG it's (data, timestamps), but it's the opposite for acc and gyro: (timestamp, data). These could be made the same.

Maybe is a dummy detail but I'll ask it anyway: should it be (data, timestamps) or (timestamps, data)? I think the second one is more intuitive, but if we use the first one it will be backward-compatible.


> We could simplify the class API by removing the eeg, control, telemetry, accelero and giro arguments, and instead subscribe to the stream if there is a valid callback argument for the corresponding stream parameter, e.g., if callback_eeg is not None, then subscribe to the EEG stream; if callback_eeg is None though don't subscribe to it.

Done. I left `enable_<data>` attributes (data is eeg, acc, etc), in case in the future is needed somewhere else in the class


> I guess you might have modified muse-lsl.py to test these changes? We should probably include these changes here so by default muse-lsl subscribes to all available data streams, and streams acc and gyro as well to LSL.
Similarly, it'd be great to be able to see these other streams in lsl-viewer.py by default or as an option.

I have another project where I use just the `Muse` class, so I've just tested it with simple functions that print the incoming data to the console. I can make those changes but I will take me more time, since I haven't worked with the Outlets used in muse-lsl; maybe leave it to another PR?


> Finally, for consistency with the Muse documentation, I think we should replace accelero, and giro by acc and gyro, respectively.

Done

More comments:
* I was thinking that the imu data could be devilered as a numpy array instead of a list, and the control data as a dictionary instead of a plain string. 
* I added an `ask_device_info()` method in the class, and I added comments in this method and in `ask_control()` explaining the message that is received. I checked the [available data](http://developer.choosemuse.com/tools/available-data#Global_Configuration) for Muse 2014 to deduct the meanings

**Comment by hubertjb** [comment]
@pdpino thanks for making the changes! Everything looks good.

- Callback APIs: I agree that (timestamps, data) makes more sense
- IMU data as a numpy array: makes sense to have output a numpy array to be consistent with the EEG callback
- `ask_device_info` and `ask_control`: awesome! :) Good idea for the dictionary too.

I made some of these changes and the ones I had suggested concerning `muse-lsl.py` and `lsl-viewer.py` in a separate branch to test the whole thing, so I might as well push it. Are you aware of a way I could commit to your PR? Otherwise I guess we can merge your PR to master and then I could make a separate PR on top of it.

**Comment by pdpino** [comment]
Great!
I don't know a way to commit to this PR, I think the easiest is the second option you mention, although I'm not an expert on PRs.
Let me know if there are changes left to do in this PR :smile:

**Comment by hubertjb** [comment]
@alexandrebarachant I think this PR can be merged! I'll make another one once it is merged that will include LSL outlets for acc and gyro, and lsl-viewer support.

**Comment by alexandrebarachant** [comment]
perfect !

**Comment by xloem** [comment]
in my project I was using rational fractions for data precision, and the gyroscope scale doesn't appear to be.  I'm very curious where this number came from.  Has anybody compared the values with those output by muse direct or mind monitor?

**Pull request merged**
