### PR TITLE
Add accelerometer and Gyroscope

### PR DESCRIPTION
**Pull request by TheChapu**
I added functions to get Acc and Gyro data

### CODE REVIEW

**Comment by alexandrebarachant** [comment]
great. i will review it later today.

**Comment by TheChapu** [comment]
Great!

**Comment by TheChapu** [comment]
Hello, have you done tests?

**Comment by TheChapu** [comment]
Hi @alexandrebarachant 
How are you?

Could you try the code?

**Comment by TheChapu** [comment]
Hi

**Comment by pdpino** [comment]
Hi,

I think that the samples from the gyroscope and accelerometer should be ints, not unsigned ints. See my pull request https://github.com/alexandrebarachant/muse-lsl/pull/32, comments are welcome :smile:

**Comment by jdpigeon** [comment]
Deprecated by https://github.com/alexandrebarachant/muse-lsl/pull/93. Thanks for getting this whole thing started!

**Pull request closed without merging**
